### ISSUE TITLE
工具试用反馈

### ISSUE THREAD

**Issue by ccyabc** [king3soft/UAutoIDE#4]
1. Hierarchy不可用时刷新按钮禁用
2. 关掉界面时udriver关闭
3. 录制时其余所有功能按键禁用，回放时除暂停结束其余按键禁用，暂停时其余功能按键禁用

**建议：**
1. 控制台可通过拖动边缘改变大小
2. 上传按键提示改为选择脚本，下载按键提示改为增加脚本（测试人员好理解）
3. 增加个查看记录文件的选项，选择了右边可以切换成记录文件的输出
4. 脚本执行结束控制台输出执行完毕

**Comment by Medemus** [comment]
@ccyabc
